### ISSUE TITLE
Can't use let binding in expression twice?

### ISSUE THREAD

**Issue by Arrow7000** [xieyuheng/inet-cute#1]
Hi, thanks for creating this project!

I'm running into an error in code that, as far as I can tell, should work.

```
(define-cons thing 0)

(define-cons nil 0)
(define-cons cons 2)

(define-elim double 1)
(define-rule (nil double) nil)
(define-rule (cons double) (let head) double head cons head cons)

(define-net doubled-list
  nil thing cons thing cons thing cons thing cons double)
```

I'm trying to write code to double the length of a list.

However I'm getting the error `Undefined name: head`, which doesn't make much sense to me, since
1. I've defined `head`
2. If I use `head` only once in the expression it works fine

Is there some kind of linear typing at work here, where you can't use a let binding more than once in the rewritten graph? Or is this a compiler error?

**Comment by xieyuheng** [comment]
@Arrow7000  It is linear typing at work :)

I am happy to see that you actually write some code in this little lang.
I should write good docs, and improve the syntax design.

Thanks for trying it out~

**Comment by Arrow7000** [comment]
Thanks for responding! 

Yeah I'm really intrigued by this language – I love the Lisp-like syntax, and the instant initial and final state previews! But I am finding it really difficult to understand the syntax, since there's almost no documentation and the error messages are quite cryptic.

Are there any other resources you could point me to to learn more about how the language works?

In any case, is there a way to explicitly duplicate the `head` in my piece of code? Or is it just not possible to achieve what I'm trying to do?

**Comment by xieyuheng** [comment]
To let the syntax better reflect the semantics that I designed,
maybe I should use pure postfix syntax like Forth.

To explicitly duplicate things, we can use a primitive called `dup`.

I learned about inet from Yves Lafont's founding paper,
the only idea about this language (a humble idea comparing to inet itself),
is to use postfix syntax and a stack machine (with a stack of ports)
to build undirected graphs (the nets).

Upon reading your message, I was thinking about
writing up a manual about how to implement inet in js/ts,
just to explain how to use a stack of ports to build nets.

But I end up spent all my time working on a tool I designed for writing manuals :p
namely [readonly.link](https://readonly.link/manuals/https://readonly.link/contents/manual/en.json) and a memory helping tool called [mimor](https://readonly.link/manuals/https://mimor.app/contents/manual/en.json)
(I found myself almost forget about the details of how inet works and how my implementation works).

I will redesign the syntax and write a manual soon,
I believe you will like it, and can give me some great feedback :)

Sorry for this late reply.

**Comment by xieyuheng** [comment]
@Arrow7000 

I re-designed the syntax,
and added a linear type system to it,
and updated the playground:
- [Example playground](https://inet.run/playground/dHlwZSBOYXQgLS0gVHlwZSBlbmQKbm9kZSB6ZXJvIC0tIE5hdCA6dmFsdWUhIGVuZApub2RlIGFkZDEgTmF0IDpwcmV2IC0tIE5hdCA6dmFsdWUhIGVuZAoKbm9kZSBhZGQgTmF0IDp0YXJnZXQhIE5hdCA6YWRkZW5kIC0tIE5hdCA6cmV0dXJuIGVuZAoKcnVsZSB6ZXJvIGFkZAogIChhZGQpLWFkZGVuZAogIHJldHVybi0oYWRkKQplbmQKCnJ1bGUgYWRkMSBhZGQKICAoYWRkKS1hZGRlbmQKICAoYWRkMSktcHJldiBhZGQKICBhZGQxIHJldHVybi0oYWRkKQplbmQKCmNsYWltIG9uZSAtLSBOYXQgZW5kCmRlZmluZSBvbmUgemVybyBhZGQxIGVuZAoKY2xhaW0gdHdvIC0tIE5hdCBlbmQKZGVmaW5lIHR3byBvbmUgb25lIGFkZCBlbmQKCnR3byB0d28gYWRkIGluc3BlY3QKcnVuIGluc3BlY3Q)

Please see [tests/](https://github.com/cicada-lang/inet/tree/master/tests) for more examples :)

I also write homepage for the language,
with a little intro: [inet.run](https://inet.run)

Work in progress:

- A book called "Programming with interaction nets"
  (linked from the homepage as "Docs").
- Canvas drawing of the rules.

**Comment by xieyuheng** [comment]
@Arrow7000 

The canvas drawing is finished.

And I end up writing an article instead of a book, called "Programming with Interaction Nets":

https://readonly.link/articles/https://cdn.inet.cic.run/docs/articles/programming-with-interaction-nets.md
